In [8]:
import numpy as np
a = np.zeros(5, dtype=int)
print(a)
print(len(a))
print(a.size)

[0 0 0 0 0]
5
5


In [4]:
a[2] = 5
print(a[1:4])

[0 5 0]


In [5]:
for i in range(a.size):
    print(a[i])

0
0
5
0
0


In [10]:
n = int(input("Please enter the length of your array: "))
arr = np.zeros(n, dtype=int)
print(arr)
for i in range(n):
    x = int(input())
    arr[i] = x
print(arr)

[0 0 0 0 0]
[3 1 4 7 3]


In [12]:
arr = np.zeros((3, 2), dtype=int)
print(arr, len(arr), arr.size)

[[0 0]
 [0 0]
 [0 0]] 3 6


In [15]:
arr = np.array([-2, 45, 0, 11, -9])

for j in range(len(arr)):
    minimum = arr[j]
    min_idx = j
    for i in range(j + 1, len(arr)):
        if arr[i] < minimum:
            minimum = arr[i]
            min_idx = i
    temp = arr[j]
    arr[j] = minimum
    arr[min_idx] = temp
print(arr)            

[-9 -2  0 11 45]


In [16]:
import numpy as np
arr2D = np.zeros((3, 4), dtype=int)
print(arr2D)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [20]:
arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr2D)
print(arr2D[0])
print(arr2D[0][2])
print(arr2D[1][3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
3
8


In [24]:
print(arr2D.shape)

(3, 4)


In [27]:
for i in range(arr2D.shape[0]):
    for j in range(arr2D.shape[1]):
        print(arr2D[i][j])

1
2
3
4
5
6
7
8
9
10
11
12


In [28]:
row, column = arr2D.shape
print(row, column)

3 4


In [30]:
arr2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2D)

for i in range(arr2D.shape[0]):
    total = 0
    for j in range(arr2D.shape[1]):
        total += arr2D[i][j]
    print(total)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
10
26
42


In [34]:
arr2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
multiply2D = np.zeros((arr2D.shape[0], arr2D.shape[1]), dtype=int)
scalar = 2

for i in range(arr2D.shape[0]):
    for j in range(arr2D.shape[1]):
        multiply2D[i][j] = scalar * arr2D[i][j]
print(arr2D)        
print(multiply2D)
print(multiply2D.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
(3, 4)


                            |4 3|
A = [3 1 4]             B = |2 5|
                            |6 8|
    1 x 3<-Must be equal->3 x 2
    result will be 1 x 2

      |0 5|
A^t = |1 2|  3 x 2
      |3 4|

A = |3 2 1| 2 x 3
    |1 2 4|

The size of A . B will be 3 x 3


t     A     t     A      t     A     t     A      t     A     t     A
0,0 x 0,0 + 0,1 x 1,0    0,0 x 0,1 + 0,1 x 1,1    0,0 x 0,2 + 0,1 x 1,2        
1,0 x 0x0 + 1x1 x 1,0    1,0 x 0,1 + 1,1 x 1,1    1,0 x 0,2 + 1,1 x 1,2
2,0 x 0,0 + 2,1 x 1,0    2,0 x 0,1 + 2,1 x 1,1    2,0 x 0,2 + 2,1 x 1,2

In [58]:
A = np.array([[0, 5], [1, 2], [3, 4]])
B = np.array([[3, 2, 1], [1, 2, 4]])


def matrices_multiplication(array1, array2):
    if array1.shape[1] != array2.shape[0]:
        return "Multiplication between these matrices isn't possible"
    else:
        result_shape = np.zeros((array1.shape[0], array2.shape[1]), dtype=int)
        for i in range(result_shape.shape[0]): 
            for j in range(result_shape.shape[1]):
                sum = 0
                for k in range(array1.shape[1]): 
                    sum += array1[i][k] * array2[k][j]
                result_shape[i][j] = sum
        return result_shape
                

result = matrices_multiplication(A, B)
print(result)

[[ 5 10 20]
 [ 5  6  9]
 [13 14 19]]
