Task 1:

Take an integer N as an input from the user and create an 1D array with size N by taking each integer element as user input. Then, print the array. Next, take another integer input from the user. Resize the array and add the new integer value in the new array. Lastly, print the new array.

Hint: As you know, the size of an array is fixed and can not be changed. So, to resize an array, copy the elements of the old array to a new array of length N+1 using a loop and then add the new value to the new array.


In [21]:
import numpy as np

N = int(input("Please array size: "))
original_arr = np.zeros(N, dtype=int)

for i in range(N):
    original_arr[i] = int(input(f"Please enter the integer element no {i + 1}: "))

print(f"Original Array: {original_arr}")

new_integer = int(input("Please enter another integer"))

resized_arr = np.zeros(N + 1, dtype=int)

for j in range(len(original_arr)):
    resized_arr[j] = original_arr[j]

resized_arr[N] = new_integer

print(f"Resized Array: {resized_arr}")

Original Array: [7 1 3 9]
Resized Array: [7 1 3 9 5]


Task 2:

Take an integer N input from the user and create a 1D integer array of N numbers. Then, print the array. Next, modify the array by changing the positive numbers by 1 and the negative numbers by 0. If the element is zero, then it will be unchanged. Lastly, print the modified array.


In [20]:
import numpy as np

N = int(input("Please enter array size: "))
arr = np.zeros(N, dtype=int)

for i in range(N):
    arr[i] = int(input(f"Please enter the integer element no {i + 1}: "))

print(f"Original Array: {arr}")

for j in range(len(arr)):
    if arr[j] > 0:
        arr[j] = 1
    else:
        arr[j] = 0

print(f"After modifying: {arr}")

Original Array: [-4  0  2]
After modifying: [0 0 1]


Task 3:

Write a Python function named reverseArray that takes a NumPy Array as parameter and using loop modifies & returns the reversed array within the given array. That means inside the function you can not create a new array.


In [19]:
import numpy as np


def reverseArray(arr):
    if type(arr) != np.ndarray:
        return "This function only accepts NumPy Arrays as an argument"

    for i in range(arr.size // 2):
        temp = arr[i]
        arr[i] = arr[arr.size - (i + 1)]
        arr[arr.size - (i + 1)] = temp

    return arr


arr1 = np.array([10, 12, 20, 5, 7])
arr1 = reverseArray(arr1)
print(arr1)

[ 7  5 20 12 10]


Task 4:

Write a Python function named printPairs that takes an array of numbers and a single integer value as parameters and prints the pairs of two array elements inside the function whose sum is equal to that integer value. If no such pair is found, then print "No Pair Found".


In [18]:
import numpy as np


def printPairs(arr, int_value):
    if type(arr) != np.ndarray or type(int_value) != int:
        print("This function accepts an array of numbers and an integer value")
        return

    pair_available = False

    for i in range(len(arr)):
        for j in range(i + 1, len(arr)):
            if arr[i] + arr[j] == int_value:
                pair_available = True
                print(f"{arr[i]}, {arr[j]}")

    if not pair_available:
        print("No Pair Found")


arr3 = np.array([5, 9, 7, 6, 10])
printPairs(arr3, 18)

No Pair Found


Task 5:

Suppose, you are given two 1D NumPy arrays (vectors). Now, using a loop, find the dot product of these two arrays and print the result. If the result is even, then swap the elements in the even index of the arrays. If the result is odd, then swap the elements in the odd index of the arrays. [You may assume that the size of both the arrays will be the same. Your code should work for 1D arrays of any size. You can not use in-built dot(), sum() or @ to solve this problem.]

The dot product of two vectors is defined by the summation of element wise multiplication of those two vectors.


In [17]:
import numpy as np


def dot_n_swap(arr1, arr2):
    if type(arr1) != np.ndarray or type(arr2) != np.ndarray:
        print("This function accepts two NumPy Arrays")
        return
    elif arr1.size != arr2.size:
        print("Both the arrays must be of equal length")
        return

    dot_product = 0

    for i in range(len(arr1)):
        dot_product += arr1[i] * arr2[i]

    print(f"Dot Product: {dot_product}")

    for j in range(len(arr1)):
        if dot_product % 2 == 0:
            if j % 2 == 0:
                temp = arr1[j]
                arr1[j] = arr2[j]
                arr2[j] = temp
        else:
            if j % 2 != 0:
                temp = arr1[j]
                arr1[j] = arr2[j]
                arr2[j] = temp

    print("After Swapping:")
    print(arr1)
    print(arr2)

vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
dot_n_swap(vec1, vec2)

Dot Product: 32
After Swapping:
[4 2 6]
[1 5 3]


Task 6:

Take an integer N input from the user and create an 1D array of N numbers taking the elements as user input too. Then, print the array. Next, sort the array in the ascending order using Selection Sort technique. Lastly, print the sorted array.


In [14]:
import numpy as np

N = int(input("Please enter array size: "))
arr = np.zeros(N, dtype=int)

for i in range(N):
    arr[i] = int(input(f"Please enter the integer element no {i + 1}: "))

print(f"Original Array: {arr}")

for i in range(N):
    for j in range(i + 1, N):
        if arr[j] < arr[i]:
            temp = arr[i]
            arr[i] = arr[j]
            arr[j] = temp

print(f"Sorted Array: {arr}")

Original Array: [ 1  5  7  4  9  5 78]
Sorted Array: [ 1  4  5  5  7  9 78]


Task 7:

Write a Python function called flatten that takes a 2D array as parameter and returns an 1D array by flattening the 2D array.


In [12]:
import numpy as np


def flatten(two_d_arr):
    if type(two_d_arr) == np.ndarray and len(two_d_arr.shape) == 2:
        one_d_array = np.zeros(two_d_arr.size, dtype=int)
        index = 0
        for i in range(two_d_arr.shape[0]):
            for j in range(two_d_arr.shape[1]):
                one_d_array[index] = two_d_arr[i][j]
                index += 1
        return one_d_array
    else:
        return "This function accepts an 2D array only"


arr3 = np.array([[1, 4], [5, 6], [8, 9]])
arr4 = flatten(arr3)
print(arr4)

[1 4 5 6 8 9]


Task 8:

You are given a square matrix A of size N×N. Check whether the given matrix is an Identity matrix or not. If it is, then print "Identity matrix" or otherwise print "Not an Identity matrix". Your program should work for any given 2D Arrays of size N×N.


In [11]:
import numpy as np


def check_identity_matrix(arr):
    if type(arr) == np.ndarray and len(arr.shape) == 2:
        if arr.shape[0] == arr.shape[1]:
            count_diagonal_ones = 0
            is_identity = True
            for i in range(arr.shape[0]):
                for j in range(arr.shape[1]):
                    if i == j and arr[i][j] == 1:
                        count_diagonal_ones += 1
                    elif i != j and arr[i][j] != 0:
                        is_identity = False
            if count_diagonal_ones == len(arr) and is_identity:
                return "Identity Matrix"
            else:
                return "Not an identity matrix"
        else:
            return "This function only works for 2D Arrays of size NxN"
    else:
        return "This function accepts an 2D array only"


A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(check_identity_matrix(A))

Identity Matrix


Task 9:

You are given a 2D array A of size N×N. Print the absolute difference between the summation of its two diagonals (primary and secondary diagonal). Your program should work for any given 2D Arrays of size N×N.
You can use abs() function to calculate the absolute difference.


In [10]:
import numpy as np


def abs_diff(arr):
    if type(arr) == np.ndarray and len(arr.shape) == 2:
        if arr.shape[0] == arr.shape[1]:
            pri_dia_sum = 0
            sec_dia_sum = 0
            for i in range(arr.shape[0]):
                for j in range(arr.shape[1]):
                    if i == j:
                        pri_dia_sum += arr[i][j]
                    if j == (arr.shape[1] - 1) - i:
                        sec_dia_sum += arr[i][j]
            return abs(pri_dia_sum - sec_dia_sum)
        else:
            return "This function only works for 2D Arrays of size NxN"
    else:
        return "This function accepts an 2D array only"


A = np.array([[1, 5, 12, 1], [2, -4, 6, 7], [3, 8, 5, 9], [3, 5, 23, -6]])
print(abs_diff(A))

22


Subtask 10.1:

Suppose, you are given a matrix of dimension M×N called A. You have to transpose the matrix in a new 2D array. Finally, print the new array. Your program should work for any given 2D Arrays of size M×N.


In [9]:
import numpy as np


def transpose(arr):
    if type(arr) == np.ndarray and len(arr.shape) == 2:
        transpose = np.zeros((arr.shape[1], arr.shape[0]), dtype=int)
        for i in range(transpose.shape[0]):
            for j in range(transpose.shape[1]):
                transpose[i][j] = arr[j][i]
        return transpose
    else:
        return "This function accepts an 2D array only"


A = np.array([[1, 2, 3, 4], [1, 4, 9, 16]])
print(transpose(A))

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


Subtask 10.2:

Using the result from Subtask 10.1, calculate the gram matrix for A. You have to use loops to solve this task.


In [8]:
import numpy as np


def gram(arr):
    if type(arr) == np.ndarray and len(arr.shape) == 2:
        trans = transpose(arr)
        gram = np.zeros((trans.shape[0], arr.shape[1]), dtype=int)
        for i in range(gram.shape[0]):
            for j in range(gram.shape[1]):
                sum = 0
                for k in range(trans.shape[1]):
                    sum += trans[i][k] * arr[k][j]
                gram[i][j] = sum
        return gram
    else:
        return "This function accepts an 2D array only"


A = np.array([[1, 2, 3, 4], [1, 4, 9, 16]])
print(gram(A))

[[  2   6  12  20]
 [  6  20  42  72]
 [ 12  42  90 156]
 [ 20  72 156 272]]


Task 11:

Suppose, you are given an M×N array called A. Your task is to subtract the row and column numbers and find the absolute difference. Next, find the remainder (rounded to 2 decimal places) by dividing the absolute value by M. Now,
If remainder = 0, then find the average of the 1st row.
If remainder = 1, then find the average of the 2nd row.
If remainder = 2, then find the average of the 3rd row.
Similarly, if remainder = m-1, then find the average of the mth row.
Now multiply each element of the original array with the average to find out the final array. Finally, display the new array.


In [3]:
def process_array_and_multiply(array):
    if type(array) == np.ndarray and len(array.shape) == 2:
        M = array.shape[0]
        N = array.shape[1]
        diff = M - N

        if diff < 0:
            diff *= -1
        remainder = diff % M

        sum = 0
        for i in range(array.shape[1]):
            sum += array[remainder][i]
        average = round(sum / array.shape[1], 2)

        result_arr = np.zeros((array.shape[0], array.shape[1]), dtype="float")

        for j in range(result_arr.shape[0]):
            for k in range(result_arr.shape[1]):
                result_arr[j][k] = array[j][k] * average

        return result_arr
    else:
        return "This function accepts an 2D array only"


A = np.array([[6, 3], [1, 5]])
print(process_array_and_multiply(A))

[[27.  13.5]
 [ 4.5 22.5]]
